"""add patient_note to consultation

Revision ID: 00a52e85cb66
Revises: ef40c69ddf1f
Create Date: 2026-06-24 18:58:58.327687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a52e85cb66'
down_revision: Union[str, Sequence[str], None] = 'ef40c69ddf1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('patient_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'patient_note')
    # ### end Alembic commands ###
