"""Added health package bookings and clinic times

Revision ID: 2b1884fc639e
Revises: 4eab254f936f
Create Date: 2026-05-26 22:16:52.446511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b1884fc639e'
down_revision: Union[str, Sequence[str], None] = '4eab254f936f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_package_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_user_id', sa.UUID(), nullable=False),
    sa.Column('health_package_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', 'COMPLETED', name='healthpackagebookingstatus'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['health_package_id'], ['health_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_package_bookings_patient_user_id'), 'health_package_bookings', ['patient_user_id'], unique=False)
    op.add_column('health_packages', sa.Column('clinic_address', sa.Text(), nullable=True))
    op.add_column('health_packages', sa.Column('clinic_open_time', sa.TIME(), nullable=True))
    op.add_column('health_packages', sa.Column('clinic_close_time', sa.TIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_packages', 'clinic_close_time')
    op.drop_column('health_packages', 'clinic_open_time')
    op.drop_column('health_packages', 'clinic_address')
    op.drop_index(op.f('ix_health_package_bookings_patient_user_id'), table_name='health_package_bookings')
    op.drop_table('health_package_bookings')
    # ### end Alembic commands ###
