"""updated partner table

Revision ID: 2dc084289579
Revises: a1c48d869b6c
Create Date: 2026-05-17 16:45:56.294832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc084289579'
down_revision: Union[str, Sequence[str], None] = 'a1c48d869b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('partners_user_id_key'), 'partners', type_='unique')
    op.drop_constraint(op.f('partners_user_id_fkey'), 'partners', type_='foreignkey')
    op.drop_column('partners', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('partners_user_id_fkey'), 'partners', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('partners_user_id_key'), 'partners', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
