"""Linked partners to users and patients to partners

Revision ID: 497f4a0e8d7e
Revises: 6ec1087f985f
Create Date: 2026-05-22 22:21:17.494356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497f4a0e8d7e'
down_revision: Union[str, Sequence[str], None] = '6ec1087f985f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'partners', ['user_id'])
    op.create_foreign_key(None, 'partners', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('patients', sa.Column('partner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'patients', 'partners', ['partner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'partner_id')
    op.drop_constraint(None, 'partners', type_='foreignkey')
    op.drop_constraint(None, 'partners', type_='unique')
    op.drop_column('partners', 'user_id')
    # ### end Alembic commands ###
