"""Updated lab test time columns and added bookings

Revision ID: 4eab254f936f
Revises: c334b44ca773
Create Date: 2026-05-26 19:50:29.842004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4eab254f936f'
down_revision: Union[str, Sequence[str], None] = 'c334b44ca773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_test_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_user_id', sa.UUID(), nullable=False),
    sa.Column('lab_test_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', 'COMPLETED', name='labtestbookingstatus'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lab_test_id'], ['lab_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_test_bookings_patient_user_id'), 'lab_test_bookings', ['patient_user_id'], unique=False)
    op.add_column('lab_tests', sa.Column('clinic_address', sa.Text(), nullable=True))
    op.add_column('lab_tests', sa.Column('clinic_open_time', sa.TIME(), nullable=True))
    op.add_column('lab_tests', sa.Column('clinic_close_time', sa.TIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_tests', 'clinic_close_time')
    op.drop_column('lab_tests', 'clinic_open_time')
    op.drop_column('lab_tests', 'clinic_address')
    op.drop_index(op.f('ix_lab_test_bookings_patient_user_id'), table_name='lab_test_bookings')
    op.drop_table('lab_test_bookings')
    # ### end Alembic commands ###
