"""Added prescription URL to consultations

Revision ID: 6ec1087f985f
Revises: a894e9c0b854
Create Date: 2026-05-21 00:04:56.739718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec1087f985f'
down_revision: Union[str, Sequence[str], None] = 'a894e9c0b854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('prescription_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'prescription_url')
    # ### end Alembic commands ###
