"""add image_url in prescriptions table

Revision ID: 9cf2d910fd25
Revises: ff8e0f17124f
Create Date: 2026-04-03 13:24:09.267092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf2d910fd25'
down_revision: Union[str, Sequence[str], None] = 'ff8e0f17124f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'image_url')
    # ### end Alembic commands ###
