"""Restore partner columns

Revision ID: 9fdf9f21a0d5
Revises: 497f4a0e8d7e
Create Date: 2026-05-22 22:58:29.979482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fdf9f21a0d5'
down_revision: Union[str, Sequence[str], None] = '497f4a0e8d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ADDED: server_default='OTHER'
    op.add_column('partners', sa.Column('partner_type', sa.Enum('PHARMACY', 'LABORATORY', 'HOSPITAL', 'CLINIC', 'OTHER', name='partnertype'), server_default='OTHER', nullable=False))
    
    # ADDED: server_default='PENDING'
    op.add_column('partners', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED', name='partnerstatus'), server_default='PENDING', nullable=False))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'status')
    op.drop_column('partners', 'partner_type')
    # ### end Alembic commands ###