"""Added corporate coupon restriction features

Revision ID: e19b1ab90e05
Revises: e11fc2b9f7fa
Create Date: 2026-05-25 18:16:18.936645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19b1ab90e05'
down_revision: Union[str, Sequence[str], None] = 'e11fc2b9f7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('partner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'coupons', 'partners', ['partner_id'], ['id'], ondelete='CASCADE')
    
    # ADDED: server_default='10.00'
    op.add_column('partners', sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), server_default='10.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'discount_percentage')
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.drop_column('coupons', 'partner_id')
    # ### end Alembic commands ###