"""added lab test slots and availability

Revision ID: ef40c69ddf1f
Revises: f08597a9b680
Create Date: 2026-06-01 22:39:31.985148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef40c69ddf1f'
down_revision: Union[str, Sequence[str], None] = 'f08597a9b680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_test_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lab_test_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['lab_test_id'], ['lab_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lab_test_bookings', sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), nullable=False))
    op.drop_column('lab_test_bookings', 'scheduled_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_test_bookings', sa.Column('scheduled_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('lab_test_bookings', 'scheduled_at')
    op.drop_table('lab_test_availability')
    # ### end Alembic commands ###
